### PR TITLE
Fix some CLI UX issues

### LINKED ISSUE #1: Using `.` for replace should work
Running
`xk6 build --with something/else=.`

inside the directory of an extension should work instead you will get 
```
go mod: -replace=github.com/mstoykov/xk6-counter=.: invalid new path: malformed import path ".": invalid path element "."
```

### PR DESCRIPTION
**Pull request by imiric**
This closes #1, addresses the `PATH` issue mentioned in https://github.com/k6io/xk6/issues/2#issuecomment-736506458, fixes `go list -m all` for modules with vendored dependencies, and does some README cleanup. It's easier to review by commit, as I didn't want to create 4 separate PRs :)

We don't have automated tests for this (maybe we should?), but I confirmed it working as expected locally.

### CODE REVIEW

File: cmd/xk6/main.go [hunk 1]
```diff
@@ -175,7 +182,7 @@ func runDev(ctx context.Context, args []string) error {
 	// and since this tool is a carry-through for the user's actual
 	// go.mod, we need to transfer their replace directives through
 	// to the one we're making
-	cmd = exec.Command("go", "list", "-m", "-f={{if .Replace}}{{.Path}} => {{.Replace}}{{end}}", "all")
+	cmd = exec.Command("go", "list", "-mod=readonly", "-m", "-f={{if .Replace}}{{.Path}} => {{.Replace}}{{end}}", "all")
```
Comment (imiric) [inline cmd/xk6/main.go:185]: Not sure if this can be considered a fix, but at least it doesn't fail when run from a vendored module directory.

File: README.md [hunk 2]
```diff
@@ -94,11 +96,11 @@ The race detector can be enabled by setting `XK6_RACE_DETECTOR=1`.
 
 ```go
 builder := xk6.Builder{
-	k6Version: "v2.0.0",
+	k6Version: "v0.29.0",
 	Plugins: []xk6.Dependency{
```
Comment (imiric) [inline README.md:100]: There's a lot of mention of "plugins" still, but not sure if we should bother with converting them all to "extensions".

File: cmd/xk6/main.go [hunk 3]
```diff
@@ -139,9 +146,9 @@ func runBuild(ctx context.Context, args []string) error {
 
 func getK6OutputFile() string {
 	if runtime.GOOS == "windows" {
-		return "k6.exe"
+		return ".\\k6.exe"
 	}
-	return "k6"
+	return "./k6"
```
Comment (MStoykov) [inline cmd/xk6/main.go:151]: I am more inclined to have runDev use a temporary place for the k6 binary instead of overwriting the one in the current directory and then ... possibly deleting it

File: README.md (hunk 2 above)
Comment (MStoykov) [reply README.md:100]: I am for `s/plugin/extension/`

**Review by MStoykov — APPROVED** [review]
LGTM. I left 2 nitpicks

File: cmd/xk6/main.go (hunk 3 above)
Comment (imiric) [reply cmd/xk6/main.go:151]: I slightly disagree. I get the overwriting/deletion concern, but this is meant to help with quick dev iterations when run from an extension repo, and it's much easier to have the binary in the CWD than in a temp dir somewhere... If you care about where it's written, you should use `xk6 build --output` instead.

File: README.md (hunk 2 above)
Comment (imiric) [reply README.md:100]: Agreed, let's do this in #7.

File: cmd/xk6/main.go (hunk 3 above)
Comment (MStoykov) [reply cmd/xk6/main.go:151]: But ... you delete the file after that ... unless an env variable is set - so in the majority of the cases you will just delete the file 'k6' in the local directory, nothing else.

Comment (imiric) [reply cmd/xk6/main.go:151]: Right, and if `XK6_SKIP_CLEANUP` is set then I'll have to hunt down the binary in a temp dir, which is more annoying than it overwriting/deleting `./k6`, that should've been produced by a previous `xk6` run anyway.

@na-- Tie breaker? 😄

Comment (MStoykov) [reply cmd/xk6/main.go:151]: The path is literally a few lines above 
image

**Review by na-- — APPROVED** [review]

File: cmd/xk6/main.go (hunk 3 above)
Comment (imiric) [reply cmd/xk6/main.go:151]: I guess we can resolve this later :)
